java_binary(
  name = "Kmp",
  srcs = ["Kmp.java"],
)

java_library(
  name = "kmp_exercise",
  srcs = ["KmpExercise.java"],
)

java_test(
  name = "KmpExerciseTest",
  srcs = ["KmpExerciseTest.java"],
  deps = [":kmp_exercise"],
)
