cc_binary(
  name = "arrays",
  srcs = ["arrays.c"],
  deps = [
    "//c/helpers:io_helper",
    "//c/helpers:array_helper",
    ],
)

cc_binary(
  name = "2d_arrays",
  srcs = ["2dArrays.c"],
  deps = ["//c/helpers:io_helper"],
)
