cc_binary(
    name = "arrays",
    srcs = ["arrays.cpp"],
)

cc_binary(
    name = "c_pointers",
    srcs = ["c-pointers.cpp"],
)

cc_binary(
    name = "cpp_style",
    srcs = ["cpp-style.cpp"],
)

cc_binary(
    name = "structs",
    srcs = ["structs.cpp"],
)

cc_binary(
    name = "templates",
    srcs = ["templates.cpp"],
)