package(
    default_visibility = ["//c:__subpackages__"],
)
cc_library(
    name = "array_helper",
    srcs = ["arrayhelper.c"],
    hdrs = ["arrayhelper.h"],
)

cc_library(
    name = "io_helper",
    srcs = ["iohelper.c"],
    hdrs = ["iohelper.h"],
)

cc_library(
    name = "stack",
    srcs = ["stack.c"],
    hdrs = ["stack.h"],
)