java_binary(
    name = "Main",
    srcs = ["Main.java"],
    deps = [":graph"],

)

java_library(
    name = "graph",
    srcs = [
        "Graph.java",
        "GraphNode.java",
        "Edge.java",
        "BfsConfig.java",
        "BfsResult.java",
        "BfsStates.java",
        "VertexState.java",
    ],
)